lib/sunshine_web/router.ex
defmodule SunshineWeb.Router do
  use SunshineWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SunshineWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", LoginController, only: [:index, :create]
    resources "/net_error", NetworkErrorCodeController, only: [:index, :create]
    get "/bravo", BravoController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SunshineWeb do
  #   pipe_through :api
  # end
end

lib/sunshine_web_web/router.ex
defmodule SunshineWebWeb.Router do
  use SunshineWebWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SunshineWebWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", LoginController, only: [:index, :create]
    get "/bravo", BravoController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SunshineWebWeb do
  #   pipe_through :api
  # end
end

lib/sunshine/application.ex
defmodule Sunshine.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the endpoint when the application starts
      supervisor(SunshineWeb.Endpoint, []),
      worker(Sunshine.Repo, []),
      # Start your own worker by calling: Sunshine.Worker.start_link(arg1, arg2, arg3)
      # worker(Sunshine.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Sunshine.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    SunshineWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/sunshine/models/user.ex
defmodule Sunshine.User do
  alias Session

  def current_user(conn) do
    Plug.Conn.get_session conn, :current_user
  end

  def logged_in?(conn) do
    !!(current_user(conn))
  end

  def login(params) do
    case authenticate_login_pass(params["password"]) do
      true ->
        {:ok, "user1"}
      _ ->
        :error
    end
  end

  def solve_net_error(params) do
    case authenticate_net_error(params["password"]) do
      true ->
        {:ok, "userFinal"}
      _ ->
        :error
    end
  end


  defp authenticate_net_error(password) do
    password_check_en =
      :crypto.hash(:sha256, "anchor") |> Base.encode16 |> String.downcase
    password_check_he =
      :crypto.hash(:sha256, "עוגן") |> Base.encode16 |> String.downcase
    encrypted_password =
      :crypto.hash(:sha256, password) |> Base.encode16 |> String.downcase
    (encrypted_password == password_check_en) ||
      (encrypted_password == password_check_he)
  end


  defp authenticate_login_pass(password) do
    password_check =
      :crypto.hash(:sha256, "ATGC") |> Base.encode16 |> String.downcase
    encrypted_password =
      :crypto.hash(:sha256, password) |> Base.encode16 |> String.downcase
    (encrypted_password == password_check)
  end
end

lib/sunshine/repo.ex
defmodule Sunshine.Repo do
  use Ecto.Repo, otp_app: :sunshine, adapter: Ecto.Adapters.Postgres
end

lib/sunshine_web/controllers/bravo_controller.ex
defmodule SunshineWeb.BravoController do
  use SunshineWeb, :controller

  def index(conn, _params) do
    case Sunshine.User.logged_in?(conn) do
      true ->  render conn, "index.html"
      false -> conn |> redirect(to: "/")
    end
  end
end

lib/sunshine_web/controllers/login_controller.ex
defmodule SunshineWeb.LoginController do
  use SunshineWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def create(conn, params) do
    case Sunshine.User.login(params["login"]) do
      {:ok, user_id} ->
        conn
        |> put_session(:current_user, user_id)
        |> put_flash(:info, "Logged in")
        |> redirect(to: "/net_error")

      :error ->
        conn
        |> put_flash(:error, "Invalid Password!")
        |> render("index.html")
    end
  end
end

lib/sunshine_web/controllers/network_error_code_controller.ex
defmodule SunshineWeb.NetworkErrorCodeController do
  use SunshineWeb, :controller

  def index(conn, _params) do
    case Sunshine.User.logged_in?(conn) do
      true ->  render conn, "index.html"
      false -> conn |> redirect(to: "/")
    end
  end

  def create(conn, params) do
    case Sunshine.User.solve_net_error(params["login"]) do
      {:ok, user_id} ->
        conn
        |> put_session(:current_user, user_id)
        |> put_flash(:info, "Yea! You did it!")
        |> redirect(to: "/bravo")

      :error ->
        conn
        |> put_flash(:error, "Invalid Code!")
        |> render("index.html")
    end
  end
end

lib/sunshine_web/views/bravo_view.ex
defmodule SunshineWeb.BravoView do
  use SunshineWeb, :view
end

lib/sunshine_web/views/error_view.ex
defmodule SunshineWeb.ErrorView do
  use SunshineWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/sunshine_web/views/layout_view.ex
defmodule SunshineWeb.LayoutView do
  use SunshineWeb, :view
end

lib/sunshine_web/views/login_view.ex
defmodule SunshineWeb.LoginView do
  use SunshineWeb, :view
end

lib/sunshine_web/views/network_error_code_view.ex
defmodule SunshineWeb.NetworkErrorCodeView do
  use SunshineWeb, :view
end

lib/sunshine_web_web/controllers/bravo_controller.ex
defmodule SunshineWebWeb.BravoController do
  use SunshineWebWeb, :controller

  def index(conn, _params) do
    case conn |> User.logged_in? do
      true -> render conn, "index.html"
      false -> conn |> redirect(to: "/")
    end
  end
end

lib/sunshine_web_web/controllers/login_controller.ex
defmodule SunshineWebWeb.LoginController do
  use SunshineWebWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def create(conn, params) do
    case User.login(params, Blog.Repo) do
      {:ok, user} ->
        conn
        |> put_session(:current_user, user)
        |> put_flash(:info, "Logged in")
        |> redirect(to: "/bravo")
      :error ->
        conn
        |> put_flash(:info, "Wrong email or password")
        |> render("index.html")
    end
  end
end

lib/sunshine_web_web/views/error_view.ex
defmodule SunshineWebWeb.ErrorView do
  use SunshineWebWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/sunshine_web/templates/bravo/index.html.eex
<div class="jumbotron">
  <h1> You Got It! </h1>
</div>

lib/sunshine_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Genetic Remote Mailer | Global Medical DWH</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="wrapper">
      <div class="container">

        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>

      </div> <!-- /container -->
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/sunshine_web/templates/login/index.html.eex
<h2>Enter Genetic Code Sequence</h2>

<%= form_for @conn, login_path(@conn, :create), [as: :login], fn f -> %>

  <div class="form-group">
    <label>Gentic code:</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Test Antidote Sequence", class: "btn btn-primary" %>
  </div>

  <%
    error = get_flash(@conn, :error)
  %>
  <%= if error do %>
    <div class="alert alert-danger" role="alert"><%= error %></div>
  <% end %>
<% end %>

lib/sunshine_web/templates/network_error_code/index.html.eex
<h2>Genetic Sequence Correct!</h2>
<h3>You're all healed, you're not longer infected!</h3>
<br />
<hr style="background-scolor: #0f0f0f;"/>
<br />
<h2>Network Blocked</h2>
<h4>Please enter the access code to send the sequence:</h4>

<div style="text-align: center;" >
  <h3>:מפתח לצופן</h3>
  <img src="<%= static_path(@conn, "/images/code.jpg") %>" 
        style="height: 50%; width: 50%;"/>
</div>
<%= form_for @conn, network_error_code_path(@conn, :create), [as: :login], fn f -> %>

  <div class="form-group">
    <label>Access Code</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Send To HQ", class: "btn bt-large btn-primary" %>
  </div>

  <%
    error = get_flash(@conn, :error)
  %>
  <%= if error do %>
    <div class="alert alert-danger" 
      role="alert"><%= error %></div>
  <% end %>
<% end %>

lib/sunshine_web_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello SunshineWeb!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <span>Welcome :P</span>
      </header>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>